### ISSUE TITLE
Package name invalid

### ISSUE THREAD

**Issue by johaziel** [serpapi/google-search-results-php#5]
Hi, I tried to submit the project to packagist.org to get it work with an other composer project but I got this error.

> The package name SerpAPI/google-search-results-php is invalid, it should not contain uppercase characters. We suggest using serp-api/google-search-results-php instead.

Please change the name of the package 
Regards
Jo

**Comment by hartator** [comment]
Will look into that. Thanks for reporting.

**Comment by jvmvik** [comment]
I got it. The package name must be all lowercase.

**Comment by jvmvik** [comment]
This is now fixed.
https://packagist.org/packages/serpapi/google-search-results-php
